### ISSUE TITLE
Roberta experiment failed

### ISSUE THREAD

**Issue by llCurious** [DachengLi1/MPCFormer#2]
Hey, @DachengLi1 . I try to run the distillation experiments for Roberta-base model. However, I notice that you have commented out TinyRobretaxxx model. I try to run this model and several errors show up, e.g., `is_torch_greater_than_1_6` is missing, `self.position_embeddings = nn.Embedding(
            config.max_position_embeddings, config.hidden_size, padding_idx=self.padding_idx
        )` incurs error: `embedding(): argument 'indices' (position 2) must be Tensor, not NoneType

Do you have any ideas?

**Comment by DachengLi1** [comment]
@RulinShao Can you look into this?

**Comment by llCurious** [comment]
Hey, any updates?

**Comment by DachengLi1** [comment]
@llCurious Hi good catch, we found that the current Roberta file is the wrong version. The Bert one should be correct, can you try that instead? We did almost the same thing to Roberta as Bert one. We can try to recover the Roberta file, but it will likely take a while due to our limited capacity. But feel free to send us an email if you really want to use Roberta as opposed to Bert. Thanks!
